/** Common countries for healthcare workforce profiles and job listings. */
export const COUNTRIES = [
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'New Zealand',
  'Ireland',
  'Germany',
  'France',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Spain',
  'Italy',
  'Portugal',
  'Poland',
  'Austria',
  'India',
  'Philippines',
  'Singapore',
  'United Arab Emirates',
  'Saudi Arabia',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Brazil',
  'Mexico',
  'Japan',
  'South Korea',
] as const;
